[project]
name = 'Sani-trust'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.Sani-trust]
path = 'contracts/Sani-trust.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'

[contracts.health-insurance]
path = 'contracts/health-insurance.clar'
clarity_version = 3
epoch = 3.1
